# Generated by Django 5.2.8 on 2026-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sub_role',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('support_agent', 'Support Agent')], default='receptionist', max_length=20),
        ),
    ]
