# Generated by Django 5.2.8 on 2026-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0005_alter_doctor_phone'),
        ('patients', '0006_patient_allergies_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'date', 'time'), name='unique_active_appointment'),
        ),
    ]
